// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: crypto.proto

package crypto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CryptoRate_GetDataStreaming_FullMethodName = "/CryptoRate/GetDataStreaming"
)

// CryptoRateClient is the client API for CryptoRate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CryptoRateClient interface {
	GetDataStreaming(ctx context.Context, in *Request, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Response], error)
}

type cryptoRateClient struct {
	cc grpc.ClientConnInterface
}

func NewCryptoRateClient(cc grpc.ClientConnInterface) CryptoRateClient {
	return &cryptoRateClient{cc}
}

func (c *cryptoRateClient) GetDataStreaming(ctx context.Context, in *Request, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CryptoRate_ServiceDesc.Streams[0], CryptoRate_GetDataStreaming_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Request, Response]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CryptoRate_GetDataStreamingClient = grpc.ServerStreamingClient[Response]

// CryptoRateServer is the server API for CryptoRate service.
// All implementations must embed UnimplementedCryptoRateServer
// for forward compatibility.
type CryptoRateServer interface {
	GetDataStreaming(*Request, grpc.ServerStreamingServer[Response]) error
	mustEmbedUnimplementedCryptoRateServer()
}

// UnimplementedCryptoRateServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCryptoRateServer struct{}

func (UnimplementedCryptoRateServer) GetDataStreaming(*Request, grpc.ServerStreamingServer[Response]) error {
	return status.Errorf(codes.Unimplemented, "method GetDataStreaming not implemented")
}
func (UnimplementedCryptoRateServer) mustEmbedUnimplementedCryptoRateServer() {}
func (UnimplementedCryptoRateServer) testEmbeddedByValue()                    {}

// UnsafeCryptoRateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CryptoRateServer will
// result in compilation errors.
type UnsafeCryptoRateServer interface {
	mustEmbedUnimplementedCryptoRateServer()
}

func RegisterCryptoRateServer(s grpc.ServiceRegistrar, srv CryptoRateServer) {
	// If the following call pancis, it indicates UnimplementedCryptoRateServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CryptoRate_ServiceDesc, srv)
}

func _CryptoRate_GetDataStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CryptoRateServer).GetDataStreaming(m, &grpc.GenericServerStream[Request, Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CryptoRate_GetDataStreamingServer = grpc.ServerStreamingServer[Response]

// CryptoRate_ServiceDesc is the grpc.ServiceDesc for CryptoRate service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CryptoRate_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CryptoRate",
	HandlerType: (*CryptoRateServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetDataStreaming",
			Handler:       _CryptoRate_GetDataStreaming_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "crypto.proto",
}
